// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// ignore_for_file: avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVFf2zJuL41sacM3Jpe27F6hXQbE3NX8',
    appId: '1:504626750451:android:9bcd988ad4a6c3a311a886',
    messagingSenderId: '504626750451',
    projectId: 'nutriq-f6be6',
    storageBucket: 'nutriq-f6be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVFf2zJuL41sacM3Jpe27F6hXQbE3NX8',
    appId: '1:504626750451:ios:9bcd988ad4a6c3a311a886',
    messagingSenderId: '504626750451',
    projectId: 'nutriq-f6be6',
    storageBucket: 'nutriq-f6be6.firebasestorage.app',
  );
}